version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - "zookeeper"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  rest:
    image: localhost/resttest
    ports:
      - "8080:8080"
    depends_on:
      - "kafka"
      - "servicetest"
  servicetest:
    image: localhost/servicetest
    ports:
      - "9090:9090"
    depends_on:
      - "kafka"